# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x8d9742340a4E722A504a63ED84ef567a7cb41cDD"
    chainName: lark
    connections:
      - token: ethereum|basesepolia|0x37884726b773297d9a9F1d644580F959194452BF
    decimals: 18
    name: Wrapped Ether
    standard: EvmHypNative
    symbol: WETH
  - addressOrDenom: "0x37884726b773297d9a9F1d644580F959194452BF"
    chainName: basesepolia
    connections:
      - token: ethereum|lark|0x8d9742340a4E722A504a63ED84ef567a7cb41cDD
    decimals: 18
    name: Wrapped Ether
    standard: EvmHypSynthetic
    symbol: WETH
